import Head from 'next/head';
import { StyledContainer } from '../components/common_styles/Container.styled';
import Footer from '../components/Footer/Footer.component';
import Header from '../components/Header/header.component';
import MintAFace from '../components/MintAFace/MintAFace.component';

export default function Home() {
  return (
    <>
      <Header />
      <StyledContainer>
        <Head>
          <title>My ERC721 Dapp</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <MintAFace />

        <h2>All about <i>mint a face</i> project</h2>
        <p>
          This is to demonstrate how to mint an ERC721 NFT. In this sample project 
          a person can mint upto 2 Jicks NFTs at a time. There is a total supply of 100. 
          In this project i am using the hid and reveal method. At the lunch, NFTs minted 
          are hidden and only the owner of the contract can reveal the NFTs. <br/>

          This project uses <strong>Polygon mumbai testnet</strong> for low gas fees. The minting 
          process can equally be paused and unpaused by the owner.<br/>

          <strong>NB:</strong> measures are taken to ensure low gas fees. You can as well  
          <i> Check out my ERC721-A project.</i>
        </p>

      </StyledContainer>
      <Footer />
    </>
  )
}
