import Head from 'next/head';
import { StyledButton } from '../components/common_styles/Button.styled';
import { StyledContainer } from '../components/common_styles/Container.styled';
import { Flex } from '../components/common_styles/Flex.styled';
import Footer from '../components/Footer/Footer.component';
import Header from '../components/Header/header.component';
import { StyledImage } from '../components/Header/Header.styled';

export default function Home() {
  return (
    <>
      <Header />
      <StyledContainer>
        <Head>
          <title>My Portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Flex>
            <div>
                <h2>If you like what you see, send me an email</h2>
                <p>
                    You can directly send me an email by clicking on the button below or sending
                    me an email by copying my emial address and using it. <strong>mbuhdivinecho@gmail.com </strong>
                     I will get back to you asap.
                </p>
                <StyledButton bg='#ff0099' color='#fff' onClick={() => window.location = 'mailto:mbuhdivinecho@gmail.com'}>
                    Contact me
                </StyledButton>
            </div>
            <StyledImage src="/assets/profilepic.jpeg" alt="Profile picture" />
        </Flex>
      </StyledContainer>
      <Footer />
    </>
  )
}
